name: Internal tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/openeo_test_suite/lib/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/openeo_test_suite/lib/**'

jobs:
  internal-tests:
    name: "Internal tests"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: "Internal tests"
      run: pytest  src/openeo_test_suite/lib/internal-tests/
